# src/main/resources/application.yml
server:
  port: 8082
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: always

spring:
  application:
    name: auth-service

  datasource:
    url: jdbc:mysql://localhost:3306/auth_db
    username: root
    password: Password@11
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect

  main:
    allow-bean-definition-overriding: true

eureka:
  client:
    service-url:
      defaultZone: http://65.1.91.144:8761/eureka
  instance:
    prefer-ip-address: true

app:
  jwtSecret: MySecretKeyMySecretKeyMySecretKeyMySecretKey
  jwtExpirationInMs: 3600000

logging:
  level:
    org.springframework.security: DEBUG
    com.example: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
