server:
  port: 8083

spring:
  application:
    name: account-service

  datasource:
    url: jdbc:mysql://localhost:3306/auth_db
    username: root
    password: Password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

logging:
  level:
    org.springframework.security: DEBUG
