server:
  port: 8081

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      routes:
        - id: auth-service
          uri: http://13.201.177.37:8082
          predicates:
            - Path=/auth/**
        - id: account-service
          uri: http://13.201.177.37:8083
          predicates:
            - Path=/account/**
          filters:
            - JwtAuthFilter
#            - AddRequestHeader=X-Gateway-Auth, true
        - id: transaction-service
          uri: http://13.201.177.37:8084
          predicates:
            - Path=/transaction/**
          filters:
            - JwtAuthFilter

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://13.201.177.37:8761/eureka
  instance:
    prefer-ip-address: true

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    com.example: DEBUG